
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ironhand
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=ironhand
      - PGPORT=5432
    depends_on:
      - db
    restart: unless-stopped
